// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu6KPe5W8fqaRmgUwHow5GQT5FncVU-kk',
    appId: '1:130322748952:web:1b2878717f1a6e3ca3156d',
    messagingSenderId: '130322748952',
    projectId: 'whereintheworld-133f0',
    authDomain: 'whereintheworld-133f0.firebaseapp.com',
    storageBucket: 'whereintheworld-133f0.firebasestorage.app',
    measurementId: 'G-JMYESQSBY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjxNPUFLXamTGCNm9yCVVYKmOd8j6h6ks',
    appId: '1:130322748952:android:929e8638f4b70168a3156d',
    messagingSenderId: '130322748952',
    projectId: 'whereintheworld-133f0',
    storageBucket: 'whereintheworld-133f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaokn6eulUS3M6mV-8NO6V3MHz31nl7Cs',
    appId: '1:130322748952:ios:18e2e006755d12daa3156d',
    messagingSenderId: '130322748952',
    projectId: 'whereintheworld-133f0',
    storageBucket: 'whereintheworld-133f0.firebasestorage.app',
    iosBundleId: 'com.example.whereInTheWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaokn6eulUS3M6mV-8NO6V3MHz31nl7Cs',
    appId: '1:130322748952:ios:18e2e006755d12daa3156d',
    messagingSenderId: '130322748952',
    projectId: 'whereintheworld-133f0',
    storageBucket: 'whereintheworld-133f0.firebasestorage.app',
    iosBundleId: 'com.example.whereInTheWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu6KPe5W8fqaRmgUwHow5GQT5FncVU-kk',
    appId: '1:130322748952:web:9215a80a9528d21ca3156d',
    messagingSenderId: '130322748952',
    projectId: 'whereintheworld-133f0',
    authDomain: 'whereintheworld-133f0.firebaseapp.com',
    storageBucket: 'whereintheworld-133f0.firebasestorage.app',
    measurementId: 'G-EEDDMQSLWJ',
  );
}
